
--Q1. What is the total revenue generated by male vs. female customers?
SELECT Gender as Customer, SUM(purchase_amount) AS Total
FROM customer
GROUP BY gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT Customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT avg(purchase_amount) from customer)


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5
	item_purchased, ROUND(AVG(review_rating),2) AS [Average Product Rating]
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, avg(purchase_amount) as purchase
FROM customer
WHERE shipping_type in ('Express','Standard')
GROUP BY shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status, count(customer_id) Total_customers, avg(purchase_amount) as Average_spend, 
		sum(purchase_amount) Total_spend
FROM customer
GROUP BY subscription_status


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 item_purchased,
		ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH customer_type AS (
	SELECT customer_id, previous_purchases,
	CASE
		WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases  BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal'
		END AS customer_segment
	FROM customer)

SELECT customer_segment, count(*) AS 'Number of Customers'
FROM customer_type
GROUP BY customer_segment


--Q8. What are the top 3 most purchased products within each category? 

SELECT category, item_purchased, total_orders
FROM 
	(
		SELECT category, item_purchased, count(*) as total_orders,
		RANK() OVER(
					PARTITION BY category
					ORDER BY count(*) desc
					)as rnk
		FROM  customer
		GROUP BY Category, item_purchased
	)a

WHERE rnk <= 3
ORDER BY category, total_orders desc
---------------------------------------------------------------------

WITH products AS(
		SELECT category, item_purchased, COUNT(*) AS total_orders,
				ROW_NUMBER() OVER(
					PARTITION BY category
					ORDER BY count(*) DESC
					)AS rn
		FROM customer
		GROUP BY category, item_purchased

		)

SELECT category, item_purchased, total_orders
FROM products
WHERE rn <= 3
ORDER BY  category, total_orders DESC


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) as customers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status


--Q10. What is the revenue contribution of each age group? 
SELECT age_group, SUM(purchase_amount)as total_revenue
FROM customer
GROUP BY age_group 
ORDER BY total_revenue DESC


select * from customer